// src/screens/BioweaponDetailStyle.tsx
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    gradientBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    noiseOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
        opacity: 0.3,
    },
    scrollView: {
        flex: 1,
        padding: 20,
    },
    header: {
        alignItems: 'center',
        marginBottom: 30,
        marginTop: 20,
    },
    backButton: {
        position: 'absolute',
        top: 0,
        left: 0,
        padding: 5,
        zIndex: 10,
    },
    backText: {
        fontFamily: 'Courier New',
        fontSize: 12,
        color: '#8b0000',
    },
    iconContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 3,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        backgroundColor: 'rgba(0,0,0,0.5)',
        shadowOpacity: 0.5,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 0 },
    },
    iconText: {
        fontSize: 60,
    },
    name: {
        fontFamily: 'Courier New',
        fontSize: 28,
        fontWeight: 'bold',
        textAlign: 'center',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 8,
        marginBottom: 15,
    },
    metaInfo: {
        flexDirection: 'row',
        gap: 10,
    },
    categoryBadge: {
        paddingHorizontal: 15,
        paddingVertical: 5,
        borderRadius: 20,
        borderWidth: 1,
    },
    categoryText: {
        fontFamily: 'Courier New',
        fontSize: 11,
        fontWeight: 'bold',
    },
    threatBadge: {
        paddingHorizontal: 15,
        paddingVertical: 5,
        borderRadius: 20,
    },
    threatText: {
        fontFamily: 'Courier New',
        fontSize: 11,
        color: '#ffffff',
        fontWeight: 'bold',
    },
    content: {
        paddingBottom: 100,
    },
    section: {
        marginBottom: 25,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        padding: 15,
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: '#8b0000',
    },
    sectionTitle: {
        fontFamily: 'Courier New',
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 12,
        letterSpacing: 1,
    },
    sectionText: {
        fontFamily: 'Courier New',
        fontSize: 12,
        color: '#bdc3c7',
        lineHeight: 18,
    },
    listItem: {
        flexDirection: 'row',
        marginBottom: 8,
        alignItems: 'flex-start',
    },
    bullet: {
        fontSize: 14,
        marginRight: 10,
        marginTop: 2,
    },
    listText: {
        fontFamily: 'Courier New',
        fontSize: 11,
        color: '#bdc3c7',
        flex: 1,
        lineHeight: 16,
    },
    containmentSection: {
        backgroundColor: 'rgba(139, 0, 0, 0.2)',
    },
    containmentText: {
        fontFamily: 'Courier New',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 10,
        borderWidth: 1,
        borderRadius: 4,
        letterSpacing: 1,
    },
    triviaItem: {
        flexDirection: 'row',
        marginBottom: 12,
        paddingLeft: 10,
        borderLeftWidth: 1,
        borderLeftColor: '#8b0000',
    },
    triviaNumber: {
        fontFamily: 'Courier New',
        fontSize: 10,
        fontWeight: 'bold',
        marginRight: 10,
        width: 25,
    },
    triviaText: {
        fontFamily: 'Courier New',
        fontSize: 11,
        color: '#ecf0f1',
        flex: 1,
        lineHeight: 16,
    },
    firstAppearance: {
        backgroundColor: '#1a0000',
        padding: 15,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    appearanceLabel: {
        fontFamily: 'Courier New',
        fontSize: 10,
        color: '#7f8c8d',
        marginBottom: 5,
    },
    appearanceText: {
        fontFamily: 'Courier New',
        fontSize: 13,
        color: '#8b0000',
        fontWeight: 'bold',
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#000000',
        padding: 10,
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#8b0000',
    },
    footerText: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#ff0000',
        fontWeight: 'bold',
    },
    footerSubtext: {
        fontFamily: 'Courier New',
        fontSize: 8,
        color: '#7f8c8d',
        marginTop: 2,
    },
});