import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#050505',
    },
    deepVeil: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(80, 6, 10, 0.16)',
    },
    scrollView: {
        flex: 1,
        height: '100%',
    },
    contentContainer: {
        flexGrow: 1,
        paddingHorizontal: width >= 780 ? 44 : 16,
        paddingTop: 48,
        paddingBottom: 44,
    },
    backButton: {
        alignSelf: 'flex-start',
        marginBottom: 18,
        paddingVertical: 8,
    },
    backText: {
        color: '#d6c7c7',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 1,
    },
    headerBlock: {
        marginBottom: 22,
        maxWidth: 920,
    },
    kicker: {
        color: '#e5383b',
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 2,
        marginBottom: 8,
    },
    title: {
        color: '#fff1f1',
        fontSize: 34,
        fontWeight: '900',
        letterSpacing: 1.4,
        marginBottom: 10,
    },
    subtitle: {
        color: '#cabcbc',
        fontSize: 15,
        lineHeight: 24,
        maxWidth: 840,
    },
    stateText: {
        color: '#f4e8e8',
        fontSize: 14,
        fontWeight: '800',
        marginBottom: 12,
    },
    errorText: {
        color: '#ff9b9b',
        fontSize: 13,
        fontWeight: '700',
        lineHeight: 20,
        marginBottom: 14,
    },
    chapterCard: {
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
        borderRadius: 10,
        borderWidth: 1,
        padding: width >= 780 ? 26 : 18,
        marginBottom: 18,
        overflow: 'hidden',
        shadowOpacity: 0.34,
        shadowOffset: { width: 0, height: 14 },
        shadowRadius: 28,
        elevation: 6,
        position: 'relative',
    },
    chapterGlow: {
        position: 'absolute',
        top: -70,
        right: -70,
        width: 220,
        height: 220,
        borderRadius: 110,
    },
    chapterTop: {
        flexDirection: width >= 620 ? 'row' : 'column',
        alignItems: width >= 620 ? 'center' : 'flex-start',
        marginBottom: 18,
    },
    chapterNumberBox: {
        width: 58,
        height: 58,
        borderRadius: 8,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.28)',
        marginRight: width >= 620 ? 16 : 0,
        marginBottom: width >= 620 ? 0 : 14,
    },
    chapterNumber: {
        fontSize: 18,
        fontWeight: '900',
        letterSpacing: 1,
    },
    chapterHeading: {
        flex: 1,
        minWidth: 0,
    },
    period: {
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 1.4,
        marginBottom: 6,
        textTransform: 'uppercase',
    },
    chapterTitle: {
        color: '#ffffff',
        fontSize: width >= 780 ? 26 : 22,
        fontWeight: '900',
        lineHeight: width >= 780 ? 32 : 28,
        marginBottom: 8,
    },
    focusText: {
        color: '#d8cdcd',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        textTransform: 'uppercase',
    },
    characterStrip: {
        borderWidth: 1,
        borderRadius: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.24)',
        paddingHorizontal: 16,
        paddingVertical: 14,
        marginBottom: 16,
        position: 'relative',
    },
    characterLabel: {
        color: '#9d9494',
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1.4,
        marginBottom: 7,
    },
    characterName: {
        color: '#fff8f8',
        fontSize: 18,
        fontWeight: '900',
        lineHeight: 24,
        marginBottom: 3,
    },
    characterRole: {
        fontSize: 12,
        fontWeight: '900',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    storyBox: {
        width: '100%',
        borderRadius: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.32)',
        paddingHorizontal: width >= 780 ? 22 : 16,
        paddingTop: 18,
        paddingBottom: 4,
        marginBottom: 16,
        position: 'relative',
    },
    storyText: {
        color: '#eee3e3',
        fontSize: 15,
        lineHeight: 25,
        marginBottom: 14,
    },
    impactBox: {
        borderLeftWidth: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.045)',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 14,
        position: 'relative',
    },
    impactLabel: {
        color: '#bdb2b2',
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1.3,
        marginBottom: 7,
    },
    impactText: {
        color: '#fff4f4',
        fontSize: 14,
        lineHeight: 23,
        fontWeight: '700',
    },
    finalCard: {
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
        backgroundColor: 'rgba(18, 18, 18, 0.98)',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#3b3b3b',
        padding: width >= 780 ? 24 : 18,
    },
    finalTitle: {
        color: '#ffffff',
        fontSize: 22,
        fontWeight: '900',
        marginBottom: 14,
    },
    finalItem: {
        color: '#e8dede',
        fontSize: 15,
        lineHeight: 24,
        marginBottom: 10,
    },
    floatingEditButton: {
        position: 'absolute',
        top: 14,
        right: 14,
        zIndex: 4,
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.44)',
    },
    boxEditButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        zIndex: 3,
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.36)',
    },
    editIcon: {
        fontSize: 19,
        fontWeight: '900',
    },
    editIconSmall: {
        fontSize: 15,
        fontWeight: '900',
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        padding: 18,
    },
    modalCard: {
        width: '100%',
        maxWidth: 820,
        maxHeight: '88%',
        alignSelf: 'center',
        backgroundColor: 'rgba(12, 12, 14, 0.98)',
        borderRadius: 10,
        borderWidth: 1,
        padding: 18,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '900',
        letterSpacing: 1,
        marginBottom: 14,
    },
    input: {
        backgroundColor: 'rgba(0, 0, 0, 0.32)',
        borderWidth: 1,
        borderColor: '#352d2d',
        borderRadius: 8,
        color: '#fff5f5',
        fontSize: 14,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 10,
    },
    textArea: {
        minHeight: 132,
        backgroundColor: 'rgba(0, 0, 0, 0.32)',
        borderWidth: 1,
        borderColor: '#352d2d',
        borderRadius: 8,
        color: '#fff5f5',
        fontSize: 14,
        lineHeight: 21,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 10,
        textAlignVertical: 'top',
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 12,
    },
    cancelButton: {
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginRight: 10,
    },
    cancelButtonText: {
        color: '#d8cccc',
        fontSize: 12,
        fontWeight: '900',
    },
    saveButton: {
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    saveButtonText: {
        color: '#ffffff',
        fontSize: 12,
        fontWeight: '900',
    },
});
