import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#070707',
    },
    backgroundOrb: {
        position: 'absolute',
        top: 40,
        right: -70,
        width: width * 0.85,
        height: 280,
        borderRadius: 180,
    },
    scrollView: {
        flex: 1,
    },
    centerState: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    stateText: {
        color: '#f5eaea',
        fontSize: 16,
        fontWeight: '700',
        lineHeight: 24,
    },
    contentContainer: {
        paddingHorizontal: 20,
        paddingTop: 52,
        paddingBottom: 40,
    },
    backButton: {
        marginBottom: 16,
    },
    backText: {
        color: '#d6c3c3',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1,
    },
    title: {
        color: '#fff5f5',
        fontSize: 30,
        fontWeight: '900',
        letterSpacing: 1.4,
        marginBottom: 10,
    },
    subtitle: {
        color: '#c0b0b0',
        fontSize: 14,
        lineHeight: 22,
    },
    headerRow: {
        flexDirection: width >= 720 ? 'row' : 'column',
        alignItems: width >= 720 ? 'center' : 'stretch',
        justifyContent: 'space-between',
        marginBottom: 14,
    },
    headerTextBlock: {
        flex: 1,
        marginRight: width >= 720 ? 16 : 0,
        marginBottom: width >= 720 ? 0 : 14,
    },
    addButton: {
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 14,
        paddingVertical: 12,
        backgroundColor: 'rgba(0, 0, 0, 0.28)',
    },
    addButtonText: {
        fontSize: 12,
        fontWeight: '900',
        letterSpacing: 0.8,
        textAlign: 'center',
    },
    inlineError: {
        color: '#ff9b9b',
        fontSize: 13,
        fontWeight: '700',
        lineHeight: 20,
        marginBottom: 12,
    },
    editHeaderButton: {
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 9,
        marginBottom: 16,
        backgroundColor: 'rgba(0, 0, 0, 0.22)',
    },
    editHeaderText: {
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0.8,
    },
    selectorRow: {
        marginBottom: 20,
    },
    selectorButton: {
        width: 150,
        backgroundColor: 'rgba(17, 17, 17, 0.92)',
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#3d3d3d',
        padding: 14,
        marginRight: 12,
    },
    selectorSelectArea: {
        flex: 1,
        paddingRight: 28,
    },
    selectorEditButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectorTitle: {
        color: '#f5eaea',
        fontSize: 13,
        fontWeight: '800',
        marginBottom: 8,
        flex: 1,
        paddingRight: 8,
    },
    selectorYear: {
        color: '#aa9c9c',
        fontSize: 11,
    },
    selectorTitleActive: {
        color: '#ffffff',
    },
    featureCard: {
        backgroundColor: 'rgba(14, 14, 18, 0.94)',
        borderRadius: 24,
        borderWidth: 1,
        padding: 20,
        marginBottom: 16,
        position: 'relative',
    },
    cardEditButton: {
        position: 'absolute',
        top: 12,
        right: 12,
        zIndex: 2,
        width: 30,
        height: 30,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.42)',
    },
    editIcon: {
        color: '#d8cccc',
        fontSize: 18,
        fontWeight: '900',
    },
    featureBadge: {
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1.4,
        marginBottom: 10,
    },
    featureTitle: {
        color: '#ffffff',
        fontSize: 24,
        fontWeight: '800',
        marginBottom: 6,
    },
    featureMeta: {
        color: '#b5a8a8',
        fontSize: 12,
        marginBottom: 14,
    },
    featureFocus: {
        color: '#f1e7e7',
        fontSize: 15,
        lineHeight: 24,
        fontWeight: '700',
    },
    textCard: {
        backgroundColor: 'rgba(11, 11, 11, 0.96)',
        borderRadius: 22,
        padding: 18,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: '#292929',
        position: 'relative',
    },
    cardLabel: {
        color: '#e5383b',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1.5,
        marginBottom: 10,
    },
    cardText: {
        color: '#d7cccc',
        fontSize: 14,
        lineHeight: 23,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.78)',
        justifyContent: 'center',
        padding: 18,
    },
    modalCard: {
        width: '100%',
        maxWidth: 760,
        maxHeight: '88%',
        alignSelf: 'center',
        backgroundColor: 'rgba(12, 12, 14, 0.98)',
        borderRadius: 10,
        borderWidth: 1,
        padding: 18,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '900',
        letterSpacing: 1,
        marginBottom: 14,
    },
    input: {
        backgroundColor: 'rgba(0, 0, 0, 0.32)',
        borderWidth: 1,
        borderColor: '#352d2d',
        borderRadius: 8,
        color: '#fff5f5',
        fontSize: 14,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 10,
    },
    textArea: {
        minHeight: 110,
        backgroundColor: 'rgba(0, 0, 0, 0.32)',
        borderWidth: 1,
        borderColor: '#352d2d',
        borderRadius: 8,
        color: '#fff5f5',
        fontSize: 14,
        lineHeight: 21,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 10,
        textAlignVertical: 'top',
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 12,
    },
    cancelButton: {
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginRight: 10,
    },
    cancelButtonText: {
        color: '#d8cccc',
        fontSize: 12,
        fontWeight: '900',
    },
    saveButton: {
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    saveButtonText: {
        color: '#ffffff',
        fontSize: 12,
        fontWeight: '900',
    },
});
