// src/screens/HomeStyle.tsx
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000000',
    },
    backgroundOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#0a0505',
    },
    scanline: {
        position: 'absolute',
        width: width,
        height: 3,
        backgroundColor: 'rgba(139, 0, 0, 0.15)',
        zIndex: 1,
    },
    glitchOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(255, 0, 0, 0.05)',
        zIndex: 2,
        pointerEvents: 'none',
    },
    scrollView: {
        flex: 1,
        padding: 20,
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#8b0000',
        paddingBottom: 10,
    },
    terminalHeader: {
        fontFamily: 'Courier New',
        fontSize: 14,
        color: '#8b0000',
        textAlign: 'center',
        letterSpacing: 2,
    },
    quarantineWarning: {
        fontFamily: 'Courier New',
        fontSize: 12,
        color: '#ff0000',
        textAlign: 'center',
        marginTop: 5,
        fontWeight: 'bold',
    },
    systemStatus: {
        backgroundColor: 'rgba(139, 0, 0, 0.1)',
        padding: 12,
        borderRadius: 4,
        marginBottom: 15,
        borderLeftWidth: 3,
        borderLeftColor: '#8b0000',
    },
    systemText: {
        fontFamily: 'Courier New',
        fontSize: 11,
        color: '#8b0000',
        marginBottom: 3,
    },
    comLink: {
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        padding: 12,
        borderRadius: 4,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#8b0000',
    },
    comLinkTitle: {
        fontFamily: 'Courier New',
        fontSize: 12,
        color: '#8b0000',
        fontWeight: 'bold',
        marginBottom: 8,
    },
    signalBar: {
        height: 4,
        backgroundColor: '#2c2c2c',
        borderRadius: 2,
        overflow: 'hidden',
        marginBottom: 5,
    },
    signalFill: {
        height: '100%',
        backgroundColor: '#8b0000',
    },
    signalText: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#7f8c8d',
    },
    terminalWindow: {
        backgroundColor: '#000000',
        borderWidth: 1,
        borderColor: '#8b0000',
        padding: 12,
        borderRadius: 4,
        marginBottom: 20,
        minHeight: 100,
    },
    terminalLine: {
        fontFamily: 'Courier New',
        fontSize: 10,
        color: '#33ff33',
        marginBottom: 4,
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: '#1a0000',
        borderRadius: 4,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#8b0000',
    },
    tabButton: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
    },
    activeTab: {
        backgroundColor: '#8b0000',
    },
    tabText: {
        fontFamily: 'Courier New',
        fontSize: 11,
        color: '#7f8c8d',
        fontWeight: 'bold',
    },
    activeTabText: {
        color: '#ffffff',
    },
    sectionContainer: {
        marginBottom: 20,
    },
    sectionTitle: {
        fontFamily: 'Courier New',
        fontSize: 16,
        color: '#8b0000',
        fontWeight: 'bold',
        marginBottom: 5,
    },
    sectionSubtitle: {
        fontFamily: 'Courier New',
        fontSize: 10,
        color: '#7f8c8d',
        marginBottom: 15,
    },
    missionCard: {
        backgroundColor: '#1a0000',
        padding: 15,
        borderRadius: 4,
        marginBottom: 10,
        borderLeftWidth: 4,
        borderLeftColor: '#8b0000',
    },
    missionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    missionTitle: {
        fontFamily: 'Courier New',
        fontSize: 14,
        color: '#ffffff',
        fontWeight: 'bold',
    },
    dangerBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 2,
        fontSize: 9,
        color: '#ffffff',
        fontWeight: 'bold',
    },
    missionDescription: {
        fontFamily: 'Courier New',
        fontSize: 11,
        color: '#bdc3c7',
        marginBottom: 8,
    },
    missionFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    missionLocation: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#f39c12',
    },
    missionReward: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#2ecc71',
    },
    survivorCard: {
        backgroundColor: '#1a0000',
        padding: 15,
        borderRadius: 4,
        marginBottom: 10,
    },
    survivorHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
    },
    survivorName: {
        fontFamily: 'Courier New',
        fontSize: 14,
        color: '#ffffff',
        fontWeight: 'bold',
        flex: 1,
    },
    survivorStatus: {
        fontFamily: 'Courier New',
        fontSize: 10,
    },
    survivorMessage: {
        fontFamily: 'Courier New',
        fontSize: 11,
        color: '#bdc3c7',
        fontStyle: 'italic',
        marginBottom: 8,
        paddingLeft: 16,
    },
    survivorMeta: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#7f8c8d',
        marginBottom: 10,
    },
    commButton: {
        backgroundColor: '#8b0000',
        padding: 8,
        borderRadius: 4,
        alignItems: 'center',
    },
    commButtonText: {
        fontFamily: 'Courier New',
        fontSize: 10,
        color: '#ffffff',
        fontWeight: 'bold',
    },
    fileCard: {
        backgroundColor: '#1a0000',
        padding: 15,
        borderRadius: 4,
        marginBottom: 10,
    },
    fileHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    fileCode: {
        fontFamily: 'Courier New',
        fontSize: 14,
        color: '#e74c3c',
        fontWeight: 'bold',
    },
    clearanceBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 2,
        fontSize: 9,
        color: '#ffffff',
        fontWeight: 'bold',
    },
    eyesOnly: {
        backgroundColor: '#8e44ad',
    },
    topSecret: {
        backgroundColor: '#c0392b',
    },
    classified: {
        backgroundColor: '#7f8c8d',
    },
    fileSubject: {
        fontFamily: 'Courier New',
        fontSize: 12,
        color: '#ffffff',
        marginBottom: 5,
    },
    fileDate: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#7f8c8d',
    },
    mapContainer: {
        backgroundColor: '#1a0000',
        padding: 15,
        borderRadius: 4,
    },
    mapGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    mapZone: {
        width: '30%',
        backgroundColor: '#000000',
        padding: 12,
        borderRadius: 4,
        alignItems: 'center',
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#8b0000',
    },
    mapZoneName: {
        fontFamily: 'Courier New',
        fontSize: 10,
        color: '#ffffff',
        marginBottom: 5,
    },
    mapZoneThreat: {
        fontSize: 16,
    },
    mapLegend: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#7f8c8d',
        textAlign: 'center',
    },
    threatAlert: {
        backgroundColor: '#1a0000',
        padding: 15,
        borderRadius: 4,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#ff0000',
    },
    threatTitle: {
        fontFamily: 'Courier New',
        fontSize: 14,
        color: '#ff0000',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
    },
    threatMessage: {
        fontFamily: 'Courier New',
        fontSize: 12,
        color: '#ffffff',
        fontStyle: 'italic',
        textAlign: 'center',
        marginBottom: 8,
    },
    threatMeta: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#7f8c8d',
        textAlign: 'center',
        marginBottom: 10,
    },
    severityBadge: {
        alignSelf: 'center',
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 2,
        backgroundColor: '#f39c12',
    },
    highSeverity: {
        backgroundColor: '#ff0000',
    },
    severityText: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#ffffff',
        fontWeight: 'bold',
    },
    footer: {
        backgroundColor: '#0a0000',
        padding: 12,
        borderRadius: 4,
        marginBottom: 15,
        borderTopWidth: 1,
        borderTopColor: '#8b0000',
    },
    systemBar: {
        marginBottom: 8,
    },
    footerText: {
        fontFamily: 'Courier New',
        fontSize: 9,
        color: '#7f8c8d',
        marginBottom: 3,
    },
    footerWarning: {
        fontFamily: 'Courier New',
        fontSize: 10,
        color: '#ff0000',
        textAlign: 'center',
        marginTop: 8,
        fontWeight: 'bold',
    },
    logoutButton: {
        backgroundColor: '#1a0000',
        padding: 15,
        borderRadius: 4,
        alignItems: 'center',
        marginBottom: 30,
        borderWidth: 1,
        borderColor: '#8b0000',
    },
    logoutText: {
        fontFamily: 'Courier New',
        fontSize: 12,
        color: '#8b0000',
        fontWeight: 'bold',
    },
});